// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq_T2K9yeSN7BBwDUJ776g0hTp0DTazgo',
    appId: '1:904198032784:web:903dc40a47ebd9eb1ab715',
    messagingSenderId: '904198032784',
    projectId: 'ecommerce-6cb79',
    authDomain: 'ecommerce-6cb79.firebaseapp.com',
    storageBucket: 'ecommerce-6cb79.firebasestorage.app',
    measurementId: 'G-Y4MQWGMKRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0VwZ5XdWh_mafB2r9aa5rUGcJ-_1woNw',
    appId: '1:904198032784:android:25973a3174a7ed0d1ab715',
    messagingSenderId: '904198032784',
    projectId: 'ecommerce-6cb79',
    storageBucket: 'ecommerce-6cb79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaCtObM7jj061CG-6y0ksmwRp_BmVnn6M',
    appId: '1:904198032784:ios:b102f8dd7979b07f1ab715',
    messagingSenderId: '904198032784',
    projectId: 'ecommerce-6cb79',
    storageBucket: 'ecommerce-6cb79.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaCtObM7jj061CG-6y0ksmwRp_BmVnn6M',
    appId: '1:904198032784:ios:b102f8dd7979b07f1ab715',
    messagingSenderId: '904198032784',
    projectId: 'ecommerce-6cb79',
    storageBucket: 'ecommerce-6cb79.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq_T2K9yeSN7BBwDUJ776g0hTp0DTazgo',
    appId: '1:904198032784:web:f6010f0afcd8b1411ab715',
    messagingSenderId: '904198032784',
    projectId: 'ecommerce-6cb79',
    authDomain: 'ecommerce-6cb79.firebaseapp.com',
    storageBucket: 'ecommerce-6cb79.firebasestorage.app',
    measurementId: 'G-JD4XK196VS',
  );
}
